"""empty message

Revision ID: 87220cf22acb
Revises: b3096a77e155
Create Date: 2020-06-15 21:43:36.164516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87220cf22acb'
down_revision = 'b3096a77e155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'deleted')
    # ### end Alembic commands ###
