"""empty message

Revision ID: bb64b9f6377e
Revises: c03d985d4346
Create Date: 2020-06-15 23:24:01.393394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb64b9f6377e'
down_revision = 'c03d985d4346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('artist', sa.Column('facebook_link', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=250), nullable=True))
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'website_link')
    op.drop_column('artist', 'seeking_venue')
    op.drop_column('artist', 'seeking_description')
    op.drop_column('artist', 'facebook_link')
    op.drop_column('artist', 'deleted')
    # ### end Alembic commands ###
