"""empty message

Revision ID: e290c62d17c5
Revises: a62445b30557
Create Date: 2020-06-14 21:45:26.437600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e290c62d17c5'
down_revision = 'a62445b30557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'deleted')
    op.drop_column('artist', 'deleted')
    # ### end Alembic commands ###
