"""empty message

Revision ID: fee051190d3c
Revises: bb64b9f6377e
Create Date: 2020-06-16 21:46:23.001264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fee051190d3c'
down_revision = 'bb64b9f6377e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('artist', sa.Column('num_of_shows', sa.Integer(), nullable=True))
    op.add_column('venue', sa.Column('num_of_shows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'num_of_shows')
    op.drop_column('artist', 'num_of_shows')
    op.drop_table('shows')
    # ### end Alembic commands ###
