"""empty message

Revision ID: fcdabbc42461
Revises: 8f2c7f286692
Create Date: 2020-09-07 15:15:10.867035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcdabbc42461'
down_revision = '8f2c7f286692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('created_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'created_time')
    # ### end Alembic commands ###
